export const SHOW_SPINNER = "SHOW_SPINNER";
export const ADD_MODULE_TOP = "ADD_MODULE_TOP";
export const ADD_MODULE_BOTTOM = "ADD_MODULE_BOTTOM";
export const TOGGLE_VISIBILITY = "TOGGLE_VISIBILITY";
export const MOVE_TO_TRASH = "MOVE_TO_TRASH";
export const TOGGLE_CANCEL_MODAL = "TOGGLE_CANCEL_MODAL";
export const SAVE_PAGE = "SAVE_PAGE";
export const TOGGLE_ADD_MODULES_MODAL = "TOGGLE_ADD_MODULES_MODAL";
